/**
 * PDF Exporter — Professional reconciliation report as PDF
 * 
 * Generates a formatted multi-page PDF with:
 * - Cover page with session info
 * - Summary statistics
 * - Match results table (color-coded)
 * - Unmatched entries section
 * - Configuration details
 * 
 * Uses jsPDF + jspdf-autotable for table rendering.
 */

import jsPDF from 'jspdf';
import autoTable, { type RowInput, type CellDef } from 'jspdf-autotable';
import type {
  MatchResult,
  MatchGroup,
  LedgerEntry,
} from '@/types';
import {
  MATCH_TYPE_LABELS,
  MATCH_STATUS_LABELS,
} from '@/constants';

// ─── Color definitions (RGB) ─────────────────────────────────

const COLORS = {
  primary: [34, 34, 59] as [number, number, number],
  headerBg: [41, 65, 122] as [number, number, number],
  headerText: [255, 255, 255] as [number, number, number],

  matchedBg: [220, 252, 231] as [number, number, number],
  matchedText: [22, 101, 52] as [number, number, number],

  unmatchedABg: [254, 226, 226] as [number, number, number],
  unmatchedAText: [153, 27, 27] as [number, number, number],

  unmatchedBBg: [255, 237, 213] as [number, number, number],
  unmatchedBText: [154, 52, 18] as [number, number, number],

  fuzzyBg: [254, 249, 195] as [number, number, number],
  fuzzyText: [133, 100, 4] as [number, number, number],

  splitBg: [243, 232, 255] as [number, number, number],
  splitText: [88, 28, 135] as [number, number, number],

  duplicateBg: [254, 249, 195] as [number, number, number],
  duplicateText: [133, 100, 4] as [number, number, number],

  lightGray: [245, 245, 245] as [number, number, number],
  mediumGray: [156, 163, 175] as [number, number, number],
  darkText: [31, 41, 55] as [number, number, number],
  white: [255, 255, 255] as [number, number, number],
};

// ─── Export options ──────────────────────────────────────────

export interface PdfExportOptions {
  title: string;
  subtitle?: string;
  companyName?: string;
  preparedBy?: string;
  includeUnmatchedDetail: boolean;
  includeConfig: boolean;
  includePassBreakdown: boolean;
  pageSize: 'a4' | 'letter';
  orientation: 'portrait' | 'landscape';
  maxRowsPerTable: number;      // prevent enormous PDFs
}

export const DEFAULT_PDF_OPTIONS: PdfExportOptions = {
  title: 'Reconciliation Report',
  subtitle: 'Generated by LedgerMatch Pro',
  includeUnmatchedDetail: true,
  includeConfig: true,
  includePassBreakdown: true,
  pageSize: 'a4',
  orientation: 'landscape',
  maxRowsPerTable: 5000,
};

// ─── Main PDF export ─────────────────────────────────────────

export function exportMatchReportPdf(
  result: MatchResult,
  entriesA: LedgerEntry[],
  entriesB: LedgerEntry[],
  options: PdfExportOptions = DEFAULT_PDF_OPTIONS
): jsPDF {
  const doc = new jsPDF({
    orientation: options.orientation,
    unit: 'mm',
    format: options.pageSize,
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 15;
  let yPos = margin;

  // ── Page 1: Cover ──
  yPos = renderCoverPage(doc, result, options, pageWidth, pageHeight);

  // ── Page 2: Summary Statistics ──
  doc.addPage();
  yPos = margin;
  yPos = renderSummarySection(doc, result, yPos, margin, pageWidth);

  // ── Pass breakdown ──
  if (options.includePassBreakdown) {
    yPos = renderPassBreakdown(doc, result, yPos + 10, margin, pageWidth);
  }

  // ── Match results table ──
  doc.addPage();
  renderMatchTable(doc, result, entriesA, entriesB, margin, options);

  // ── Unmatched detail ──
  if (options.includeUnmatchedDetail) {
    const unmatchedA = result.matchGroups.filter(
      (mg) => mg.matchType === 'unmatched_a'
    );
    const unmatchedB = result.matchGroups.filter(
      (mg) => mg.matchType === 'unmatched_b'
    );

    if (unmatchedA.length > 0 || unmatchedB.length > 0) {
      doc.addPage();
      renderUnmatchedSection(
        doc, unmatchedA, unmatchedB, entriesA, entriesB, margin, options
      );
    }
  }

  // ── Configuration ──
  if (options.includeConfig) {
    doc.addPage();
    renderConfigSection(doc, result, margin, pageWidth);
  }

  // ── Page numbers on all pages ──
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.mediumGray);
    doc.text(
      `Page ${i} of ${totalPages}`,
      pageWidth - margin,
      pageHeight - 8,
      { align: 'right' }
    );
    doc.text(
      `Generated: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}`,
      margin,
      pageHeight - 8
    );
  }

  return doc;
}

// ─── Cover page ──────────────────────────────────────────────

function renderCoverPage(
  doc: jsPDF,
  result: MatchResult,
  options: PdfExportOptions,
  pageWidth: number,
  pageHeight: number
): number {
  const centerX = pageWidth / 2;

  // Title
  doc.setFontSize(28);
  doc.setTextColor(...COLORS.primary);
  doc.text(options.title, centerX, pageHeight * 0.3, { align: 'center' });

  // Subtitle
  if (options.subtitle) {
    doc.setFontSize(14);
    doc.setTextColor(...COLORS.mediumGray);
    doc.text(options.subtitle, centerX, pageHeight * 0.3 + 12, {
      align: 'center',
    });
  }

  // Divider line
  doc.setDrawColor(...COLORS.headerBg);
  doc.setLineWidth(0.5);
  doc.line(
    pageWidth * 0.25,
    pageHeight * 0.38,
    pageWidth * 0.75,
    pageHeight * 0.38
  );

  // Info block
  let yPos = pageHeight * 0.45;
  doc.setFontSize(11);
  doc.setTextColor(...COLORS.darkText);

  const info: [string, string][] = [
    ['Session ID', result.sessionId.substring(0, 8)],
    ['Date', new Date(result.completedAt).toLocaleDateString()],
    ['Entries (Ledger A)', result.summary.totalEntriesA.toString()],
    ['Entries (Ledger B)', result.summary.totalEntriesB.toString()],
    ['Match Rate', `${(result.summary.matchRate * 100).toFixed(1)}%`],
    ['Processing Time', `${(result.summary.processingTimeMs / 1000).toFixed(2)}s`],
  ];

  if (options.companyName) {
    info.unshift(['Company', options.companyName]);
  }
  if (options.preparedBy) {
    info.unshift(['Prepared By', options.preparedBy]);
  }

  for (const [label, value] of info) {
    doc.setFont('helvetica', 'bold');
    doc.text(`${label}:`, centerX - 30, yPos, { align: 'right' });
    doc.setFont('helvetica', 'normal');
    doc.text(value, centerX - 25, yPos);
    yPos += 8;
  }

  return yPos;
}

// ─── Summary section ─────────────────────────────────────────

function renderSummarySection(
  doc: jsPDF,
  result: MatchResult,
  yStart: number,
  margin: number,
  pageWidth: number
): number {
  let yPos = yStart;

  // Section header
  doc.setFontSize(16);
  doc.setTextColor(...COLORS.primary);
  doc.text('Summary', margin, yPos);
  yPos += 10;

  const s = result.summary;

  // Summary table
  const summaryData: RowInput[] = [
    [
      { content: 'Matched', styles: { fontStyle: 'bold' } },
      s.matchedCount.toString(),
      `${(s.matchRate * 100).toFixed(1)}%`,
    ],
    ['Unmatched (Ledger A)', s.unmatchedACount.toString(), ''],
    ['Unmatched (Ledger B)', s.unmatchedBCount.toString(), ''],
    ['Split Matches', s.splitCount.toString(), ''],
    ['Duplicates', s.duplicateCount.toString(), ''],
    [
      { content: 'Average Confidence', styles: { fontStyle: 'bold' } },
      `${s.averageConfidence}%`,
      '',
    ],
  ];

  autoTable(doc, {
    startY: yPos,
    head: [['Metric', 'Count', 'Rate']],
    body: summaryData,
    theme: 'striped',
    headStyles: {
      fillColor: COLORS.headerBg,
      textColor: COLORS.headerText,
      fontStyle: 'bold',
      fontSize: 10,
    },
    bodyStyles: {
      fontSize: 10,
      textColor: COLORS.darkText,
    },
    columnStyles: {
      0: { cellWidth: 60 },
      1: { cellWidth: 30, halign: 'right' },
      2: { cellWidth: 30, halign: 'right' },
    },
    margin: { left: margin, right: margin },
  });

  yPos = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 10;

  // Amount summary table
  const amountData: RowInput[] = [
    ['Total (Ledger A)', formatCurrency(s.totalAmountA)],
    ['Total (Ledger B)', formatCurrency(s.totalAmountB)],
    [
      { content: 'Discrepancy', styles: { fontStyle: 'bold', textColor: s.totalDiscrepancy > 0 ? COLORS.unmatchedAText : COLORS.matchedText } },
      { content: formatCurrency(s.totalDiscrepancy), styles: { fontStyle: 'bold' } },
    ],
    ['Matched Amount', formatCurrency(s.matchedAmount)],
    ['Unmatched Amount (A)', formatCurrency(s.unmatchedAmountA)],
    ['Unmatched Amount (B)', formatCurrency(s.unmatchedAmountB)],
  ];

  autoTable(doc, {
    startY: yPos,
    head: [['Amount Metric', 'Value']],
    body: amountData,
    theme: 'striped',
    headStyles: {
      fillColor: COLORS.headerBg,
      textColor: COLORS.headerText,
      fontStyle: 'bold',
      fontSize: 10,
    },
    bodyStyles: { fontSize: 10, textColor: COLORS.darkText },
    columnStyles: {
      0: { cellWidth: 60 },
      1: { cellWidth: 50, halign: 'right' },
    },
    margin: { left: margin, right: margin },
  });

  return (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY;
}

// ─── Pass breakdown ──────────────────────────────────────────

function renderPassBreakdown(
  doc: jsPDF,
  result: MatchResult,
  yStart: number,
  margin: number,
  pageWidth: number
): number {
  doc.setFontSize(14);
  doc.setTextColor(...COLORS.primary);
  doc.text('Match Pass Breakdown', margin, yStart);

  const passData: RowInput[] = result.summary.byPass.map((pass) => [
    `Pass ${pass.passNumber}`,
    pass.passName,
    pass.matchCount.toString(),
    `${pass.averageConfidence}%`,
    `${pass.timeMs.toFixed(0)}ms`,
  ]);

  autoTable(doc, {
    startY: yStart + 6,
    head: [['Pass', 'Name', 'Matches', 'Avg Confidence', 'Time']],
    body: passData,
    theme: 'striped',
    headStyles: {
      fillColor: COLORS.headerBg,
      textColor: COLORS.headerText,
      fontStyle: 'bold',
      fontSize: 9,
    },
    bodyStyles: { fontSize: 9, textColor: COLORS.darkText },
    margin: { left: margin, right: margin },
  });

  return (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY;
}

// ─── Match results table ─────────────────────────────────────

function renderMatchTable(
  doc: jsPDF,
  result: MatchResult,
  entriesA: LedgerEntry[],
  entriesB: LedgerEntry[],
  margin: number,
  options: PdfExportOptions
): void {
  const entryMapA = new Map(entriesA.map((e) => [e.id, e]));
  const entryMapB = new Map(entriesB.map((e) => [e.id, e]));

  doc.setFontSize(14);
  doc.setTextColor(...COLORS.primary);
  doc.text('Match Results', margin, margin);

  const rows: RowInput[] = [];
  const rowColors: Array<[number, number, number]> = [];

  // Limit rows for PDF sanity
  const groups = result.matchGroups.slice(0, options.maxRowsPerTable);

  for (const group of groups) {
    const entryA = group.entriesA.length > 0
      ? entryMapA.get(group.entriesA[0])
      : null;
    const entryB = group.entriesB.length > 0
      ? entryMapB.get(group.entriesB[0])
      : null;

    const bgColor = getMatchTypeColor(group.matchType);
    rowColors.push(bgColor);

    rows.push([
      MATCH_TYPE_LABELS[group.matchType] ?? group.matchType,
      `${group.confidence}%`,
      entryA?.date ?? '',
      truncate(entryA?.description ?? '', 25),
      entryA ? formatCurrency(entryA.amountAbs) : '',
      entryB?.date ?? '',
      truncate(entryB?.description ?? '', 25),
      entryB ? formatCurrency(entryB.amountAbs) : '',
      formatCurrency(group.amountDifference),
      MATCH_STATUS_LABELS[group.status] ?? group.status,
    ]);
  }

  autoTable(doc, {
    startY: margin + 6,
    head: [[
      'Type', 'Conf', 'A Date', 'A Description', 'A Amount',
      'B Date', 'B Description', 'B Amount', 'Diff', 'Status',
    ]],
    body: rows,
    theme: 'grid',
    headStyles: {
      fillColor: COLORS.headerBg,
      textColor: COLORS.headerText,
      fontStyle: 'bold',
      fontSize: 7,
      cellPadding: 2,
    },
    bodyStyles: {
      fontSize: 7,
      textColor: COLORS.darkText,
      cellPadding: 1.5,
    },
    columnStyles: {
      0: { cellWidth: 22 },
      1: { cellWidth: 12, halign: 'center' },
      2: { cellWidth: 20 },
      3: { cellWidth: 'auto' },
      4: { cellWidth: 22, halign: 'right' },
      5: { cellWidth: 20 },
      6: { cellWidth: 'auto' },
      7: { cellWidth: 22, halign: 'right' },
      8: { cellWidth: 18, halign: 'right' },
      9: { cellWidth: 16 },
    },
    didParseCell: (data) => {
      if (data.section === 'body' && data.row.index < rowColors.length) {
        data.cell.styles.fillColor = rowColors[data.row.index];
      }
    },
    margin: { left: margin, right: margin },
    showHead: 'everyPage',
  });

  if (groups.length < result.matchGroups.length) {
    const finalY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY;
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.mediumGray);
    doc.text(
      `Showing ${groups.length} of ${result.matchGroups.length} entries. Export CSV for complete data.`,
      margin,
      finalY + 5
    );
  }
}

// ─── Unmatched section ───────────────────────────────────────

function renderUnmatchedSection(
  doc: jsPDF,
  unmatchedA: MatchGroup[],
  unmatchedB: MatchGroup[],
  entriesA: LedgerEntry[],
  entriesB: LedgerEntry[],
  margin: number,
  options: PdfExportOptions
): void {
  const entryMapA = new Map(entriesA.map((e) => [e.id, e]));
  const entryMapB = new Map(entriesB.map((e) => [e.id, e]));

  doc.setFontSize(14);
  doc.setTextColor(...COLORS.primary);
  doc.text('Unmatched Entries', margin, margin);

  let yPos = margin + 8;

  // Unmatched A
  if (unmatchedA.length > 0) {
    doc.setFontSize(11);
    doc.setTextColor(...COLORS.unmatchedAText);
    doc.text(`Ledger A — ${unmatchedA.length} unmatched`, margin, yPos);

    const aRows: RowInput[] = unmatchedA
      .slice(0, options.maxRowsPerTable)
      .flatMap((mg) =>
        mg.entriesA.map((id) => {
          const entry = entryMapA.get(id);
          if (!entry) return ['', '', '', '', ''];
          return [
            entry.date ?? '',
            truncate(entry.description, 40),
            entry.debit != null ? formatCurrency(entry.debit) : '',
            entry.credit != null ? formatCurrency(entry.credit) : '',
            entry.refNumber ?? '',
          ];
        })
      );

    autoTable(doc, {
      startY: yPos + 4,
      head: [['Date', 'Description', 'Debit', 'Credit', 'Reference']],
      body: aRows,
      theme: 'striped',
      headStyles: {
        fillColor: COLORS.unmatchedAText,
        textColor: COLORS.white,
        fontStyle: 'bold',
        fontSize: 8,
      },
      bodyStyles: {
        fontSize: 8,
        textColor: COLORS.darkText,
        fillColor: COLORS.unmatchedABg,
      },
      alternateRowStyles: { fillColor: COLORS.white },
      margin: { left: margin, right: margin },
    });

    yPos = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 10;
  }

  // Unmatched B
  if (unmatchedB.length > 0) {
    // Check if we need a new page
    if (yPos > doc.internal.pageSize.getHeight() - 40) {
      doc.addPage();
      yPos = margin;
    }

    doc.setFontSize(11);
    doc.setTextColor(...COLORS.unmatchedBText);
    doc.text(`Ledger B — ${unmatchedB.length} unmatched`, margin, yPos);

    const bRows: RowInput[] = unmatchedB
      .slice(0, options.maxRowsPerTable)
      .flatMap((mg) =>
        mg.entriesB.map((id) => {
          const entry = entryMapB.get(id);
          if (!entry) return ['', '', '', '', ''];
          return [
            entry.date ?? '',
            truncate(entry.description, 40),
            entry.debit != null ? formatCurrency(entry.debit) : '',
            entry.credit != null ? formatCurrency(entry.credit) : '',
            entry.refNumber ?? '',
          ];
        })
      );

    autoTable(doc, {
      startY: yPos + 4,
      head: [['Date', 'Description', 'Debit', 'Credit', 'Reference']],
      body: bRows,
      theme: 'striped',
      headStyles: {
        fillColor: COLORS.unmatchedBText,
        textColor: COLORS.white,
        fontStyle: 'bold',
        fontSize: 8,
      },
      bodyStyles: {
        fontSize: 8,
        textColor: COLORS.darkText,
        fillColor: COLORS.unmatchedBBg,
      },
      alternateRowStyles: { fillColor: COLORS.white },
      margin: { left: margin, right: margin },
    });
  }
}

// ─── Configuration section ───────────────────────────────────

function renderConfigSection(
  doc: jsPDF,
  result: MatchResult,
  margin: number,
  pageWidth: number
): void {
  doc.setFontSize(14);
  doc.setTextColor(...COLORS.primary);
  doc.text('Matching Configuration', margin, margin);

  const c = result.config;

  const configData: RowInput[] = [
    ['Date Tolerance', `±${c.dateToleranceDays} days`],
    ['Amount Tolerance (Percent)', `±${(c.amountTolerancePercent * 100).toFixed(2)}%`],
    ['Amount Tolerance (Fixed)', `±$${c.amountToleranceFixed.toFixed(2)}`],
    ['Amount Tolerance Mode', c.amountToleranceMode],
    ['Description Threshold', `${(c.descriptionThreshold * 100).toFixed(0)}%`],
    ['Description Weights',
      `JW: ${c.descriptionWeight.jaroWinkler}, TS: ${c.descriptionWeight.tokenSort}, TC: ${c.descriptionWeight.tokenContainment}`],
    ['Polarity Mode', c.polarityMode],
    ['Enabled Passes', c.enabledPasses.join(', ')],
    ['Split Max Entries', c.splitMaxEntries.toString()],
    ['Split Time Limit', `${c.splitTimeLimitMs}ms`],
    ['Currency', c.currency],
    ['Case Sensitive Ref', c.caseSensitiveRef ? 'Yes' : 'No'],
  ];

  autoTable(doc, {
    startY: margin + 8,
    head: [['Parameter', 'Value']],
    body: configData,
    theme: 'striped',
    headStyles: {
      fillColor: COLORS.headerBg,
      textColor: COLORS.headerText,
      fontStyle: 'bold',
      fontSize: 9,
    },
    bodyStyles: { fontSize: 9, textColor: COLORS.darkText },
    columnStyles: {
      0: { cellWidth: 60, fontStyle: 'bold' },
      1: { cellWidth: 'auto' },
    },
    margin: { left: margin, right: margin },
  });
}

// ─── Helpers ─────────────────────────────────────────────────

function getMatchTypeColor(
  matchType: string
): [number, number, number] {
  switch (matchType) {
    case 'exact':
    case 'amount_date':
      return COLORS.matchedBg;
    case 'fuzzy':
      return COLORS.fuzzyBg;
    case 'split':
      return COLORS.splitBg;
    case 'unmatched_a':
      return COLORS.unmatchedABg;
    case 'unmatched_b':
      return COLORS.unmatchedBBg;
    case 'duplicate':
      return COLORS.duplicateBg;
    default:
      return COLORS.white;
  }
}

function formatCurrency(value: number): string {
  if (value === 0) return '$0.00';
  const prefix = value < 0 ? '-' : '';
  return `${prefix}$${Math.abs(value).toFixed(2).replace(/\B(?=(\d{3})+(?!\d))/g, ',')}`;
}

function truncate(str: string, maxLen: number): string {
  if (str.length <= maxLen) return str;
  return str.substring(0, maxLen - 2) + '..';
}

// ─── Download trigger ────────────────────────────────────────

export function downloadPdf(doc: jsPDF, filename: string): void {
  doc.save(filename);
}